
import React, { useState, useEffect, useCallback, useRef } from 'react';
import FileUpload from './components/FileUpload';
import Flashcard from './components/Flashcard';
import QuizCard from './components/QuizCard';
import { FlashcardData, QuizData, AppState, GenerationMode } from './types';
import { generateStudyMaterial } from './services/gemini';
import { jsPDF } from 'jspdf';

const App: React.FC = () => {
  const [state, setState] = useState<AppState>(AppState.IDLE);
  const [mode, setMode] = useState<GenerationMode>(GenerationMode.FLASHCARDS);
  const [studyData, setStudyData] = useState<any[]>([]);
  const [currentCardIndex, setCurrentCardIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  
  // Ref to store content temporarily between file select and generation
  const pendingContent = useRef<string | { mimeType: string, data: string } | null>(null);

  const simulateProgress = () => {
    setProgress(0);
    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 90) {
          clearInterval(interval);
          return 90;
        }
        return prev + 10;
      });
    }, 200);
    return interval;
  };

  const handleFileSelect = async (file: File) => {
    try {
      let content: any;
      if (file.type.startsWith('image/')) {
        const reader = new FileReader();
        const base64Promise = new Promise<string>((resolve) => {
          reader.onload = (e) => {
            const result = e.target?.result as string;
            resolve(result.split(',')[1]);
          };
        });
        reader.readAsDataURL(file);
        const base64Data = await base64Promise;
        content = { mimeType: file.type, data: base64Data };
      } else {
        content = await file.text();
      }
      
      pendingContent.current = content;
      setState(AppState.SELECTING_MODE);
    } catch (err) {
      console.error(err);
      setErrorMsg("Failed to read file. Please try a different format.");
      setState(AppState.ERROR);
    }
  };

  const startGeneration = async (selectedMode: GenerationMode) => {
    if (!pendingContent.current) return;
    
    setMode(selectedMode);
    setState(AppState.PROCESSING);
    const progressInterval = simulateProgress();

    try {
      const generatedData = await generateStudyMaterial(pendingContent.current, selectedMode);
      
      clearInterval(progressInterval);
      setProgress(100);
      
      setTimeout(() => {
        setStudyData(generatedData);
        setCurrentCardIndex(0);
        setState(AppState.VIEWING);
        pendingContent.current = null; // Clear memory
      }, 500);

    } catch (err) {
      console.error(err);
      setErrorMsg("Gemini AI failed to process the content. Please ensure the file contains readable study material.");
      setState(AppState.ERROR);
      clearInterval(progressInterval);
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const title = mode === GenerationMode.FLASHCARDS ? "Study Flashcards" : "Quiz Questions";
    
    doc.setFontSize(22);
    doc.text(title, 20, 20);
    doc.setFontSize(12);
    doc.text(`Generated by StudBud on ${new Date().toLocaleDateString()}`, 20, 30);
    
    let y = 45;
    studyData.forEach((item, index) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      
      doc.setFont("helvetica", "bold");
      doc.text(`${index + 1}. Question:`, 20, y);
      doc.setFont("helvetica", "normal");
      
      const questionLines = doc.splitTextToSize(item.question, 170);
      doc.text(questionLines, 20, y + 7);
      y += 10 + (questionLines.length * 5);

      if (mode === GenerationMode.FLASHCARDS) {
        doc.setFont("helvetica", "bold");
        doc.text("Answer:", 20, y);
        doc.setFont("helvetica", "normal");
        const answerLines = doc.splitTextToSize(item.answer, 170);
        doc.text(answerLines, 20, y + 7);
        y += 15 + (answerLines.length * 5);
      } else {
        doc.text("Options:", 20, y);
        item.options.forEach((opt: string, i: number) => {
          const prefix = opt === item.correctAnswer ? " [✓] " : " [ ] ";
          doc.text(`${prefix} ${String.fromCharCode(65 + i)}) ${opt}`, 25, y + 7 + (i * 7));
        });
        y += 45;
      }
      y += 5;
    });

    doc.save(`StudBud-${mode}-${Date.now()}.pdf`);
  };

  const handleReset = () => {
    setState(AppState.IDLE);
    setStudyData([]);
    setCurrentCardIndex(0);
    setProgress(0);
    setErrorMsg(null);
    pendingContent.current = null;
  };

  const nextCard = useCallback(() => {
    if (currentCardIndex < studyData.length - 1) {
      setCurrentCardIndex(prev => prev + 1);
    }
  }, [currentCardIndex, studyData.length]);

  const prevCard = useCallback(() => {
    if (currentCardIndex > 0) {
      setCurrentCardIndex(prev => prev - 1);
    }
  }, [currentCardIndex]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (state !== AppState.VIEWING) return;
      if (e.key === 'ArrowRight') nextCard();
      if (e.key === 'ArrowLeft') prevCard();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [state, nextCard, prevCard]);

  return (
    <div className="min-h-screen flex flex-col selection:bg-cyan-500/30">
      {/* Header */}
      <nav className="p-6 flex justify-between items-center border-b border-white/5 bg-slate-950/50 backdrop-blur-xl sticky top-0 z-50">
        <div className="flex items-center gap-2 cursor-pointer" onClick={handleReset}>
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-400 to-blue-600 shadow-[0_0_15px_rgba(34,211,238,0.5)] flex items-center justify-center">
            <span className="text-white font-bold text-lg">S</span>
          </div>
          <h1 className="text-xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
            StudBud
          </h1>
        </div>
        
        {state === AppState.VIEWING && (
          <div className="flex gap-2">
            <button 
              onClick={downloadPDF}
              className="px-4 py-2 rounded-full bg-cyan-500/10 hover:bg-cyan-500/20 border border-cyan-500/30 text-cyan-400 text-sm font-medium transition-all flex items-center gap-2"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
              </svg>
              Export PDF
            </button>
            <button 
              onClick={handleReset}
              className="px-4 py-2 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 text-sm font-medium transition-colors"
            >
              Start Over
            </button>
          </div>
        )}
      </nav>

      <main className="flex-1 flex flex-col items-center justify-center p-6 md:p-12 max-w-7xl mx-auto w-full">
        
        {state === AppState.IDLE && (
          <div className="w-full flex flex-col items-center animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="text-center mb-12">
              <h2 className="text-4xl md:text-5xl font-bold mb-4 tracking-tight">Master any subject with AI.</h2>
              <p className="text-slate-400 text-lg max-w-xl mx-auto mb-8">
                Upload your study materials to get started.
              </p>
            </div>
            <FileUpload onFileSelect={handleFileSelect} isLoading={false} />
          </div>
        )}

        {state === AppState.SELECTING_MODE && (
          <div className="w-full max-w-4xl flex flex-col items-center animate-in fade-in zoom-in-95 duration-500">
             <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4 tracking-tight text-white">Choose your study path</h2>
              <p className="text-slate-400 text-lg">How would you like to study this material?</p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full px-4">
              {/* Flashcards Option */}
              <button 
                onClick={() => startGeneration(GenerationMode.FLASHCARDS)}
                className="group relative p-8 bg-slate-900 border border-white/10 rounded-[2.5rem] hover:border-cyan-500/50 hover:bg-slate-800/50 transition-all duration-300 text-left flex flex-col items-start gap-6 shadow-2xl active:scale-[0.98]"
              >
                <div className="w-14 h-14 rounded-2xl bg-cyan-500/10 flex items-center justify-center text-cyan-400 group-hover:bg-cyan-500 group-hover:text-slate-950 transition-all duration-300 shadow-[0_0_20px_rgba(34,211,238,0.1)] group-hover:shadow-[0_0_30px_rgba(34,211,238,0.4)]">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-white mb-2">Flashcards</h3>
                  <p className="text-slate-400 leading-relaxed">
                    Classic question and answer cards. Perfect for memorizing concepts and vocabulary.
                  </p>
                </div>
                <div className="mt-auto pt-4 flex items-center gap-2 text-cyan-400 font-bold group-hover:translate-x-2 transition-transform">
                  Generate <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" />
                  </svg>
                </div>
              </button>

              {/* Quiz Option */}
              <button 
                onClick={() => startGeneration(GenerationMode.QUIZ)}
                className="group relative p-8 bg-slate-900 border border-white/10 rounded-[2.5rem] hover:border-purple-500/50 hover:bg-slate-800/50 transition-all duration-300 text-left flex flex-col items-start gap-6 shadow-2xl active:scale-[0.98]"
              >
                <div className="w-14 h-14 rounded-2xl bg-purple-500/10 flex items-center justify-center text-purple-400 group-hover:bg-purple-500 group-hover:text-slate-950 transition-all duration-300 shadow-[0_0_20px_rgba(168,85,247,0.1)] group-hover:shadow-[0_0_30px_rgba(168,85,247,0.4)]">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-white mb-2">Multiple Choice</h3>
                  <p className="text-slate-400 leading-relaxed">
                    Interactive quiz with distractors. Best for testing your understanding and application of knowledge.
                  </p>
                </div>
                <div className="mt-auto pt-4 flex items-center gap-2 text-purple-400 font-bold group-hover:translate-x-2 transition-transform">
                  Generate <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" />
                  </svg>
                </div>
              </button>
            </div>
            
            <button onClick={handleReset} className="mt-12 text-slate-500 hover:text-white transition-colors flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              Go back to upload
            </button>
          </div>
        )}

        {(state === AppState.UPLOADING || state === AppState.PROCESSING) && (
          <div className="w-full max-w-md flex flex-col items-center gap-8">
            <div className="w-full h-1 bg-white/10 rounded-full overflow-hidden">
              <div 
                className="h-full bg-gradient-to-r from-cyan-400 to-blue-500 transition-all duration-500 ease-out shadow-[0_0_15px_rgba(34,211,238,0.6)]"
                style={{ width: `${progress}%` }}
              />
            </div>
            <div className="text-center">
              <p className="text-cyan-400 font-medium animate-pulse">
                {state === AppState.UPLOADING ? 'Uploading...' : `Gemini is generating your ${mode === GenerationMode.FLASHCARDS ? 'flashcards' : 'quiz'}...`}
              </p>
              <p className="text-slate-500 text-sm mt-2">Analying concepts and crafting questions</p>
            </div>
          </div>
        )}

        {state === AppState.VIEWING && studyData.length > 0 && (
          <div className="w-full max-w-2xl animate-in fade-in zoom-in-95 duration-500">
            <div className="mb-8 text-center">
              <h2 className="text-2xl font-bold text-white mb-1">
                {mode === GenerationMode.FLASHCARDS ? 'Flashcard Review' : 'Quiz Practice'}
              </h2>
              <p className="text-slate-400 text-sm">
                Item <span className="text-cyan-400 font-mono">{currentCardIndex + 1}</span> of <span className="text-slate-300 font-mono">{studyData.length}</span>
              </p>
              <div className="w-32 h-1 bg-white/5 rounded-full mx-auto mt-4 overflow-hidden">
                <div 
                  className="h-full bg-cyan-500/50 transition-all duration-300"
                  style={{ width: `${((currentCardIndex + 1) / studyData.length) * 100}%` }}
                />
              </div>
            </div>

            <div className="relative group">
              {/* Desktop Nav */}
              <div className="absolute -left-20 top-1/2 -translate-y-1/2 hidden lg:block">
                 <button 
                  onClick={prevCard}
                  disabled={currentCardIndex === 0}
                  className={`p-4 rounded-full border border-white/10 transition-all ${currentCardIndex === 0 ? 'opacity-10 cursor-not-allowed' : 'bg-slate-900 hover:bg-slate-800 hover:border-cyan-500/50 text-white shadow-xl active:scale-95'}`}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                  </svg>
                </button>
              </div>

              <div className="absolute -right-20 top-1/2 -translate-y-1/2 hidden lg:block">
                <button 
                  onClick={nextCard}
                  disabled={currentCardIndex === studyData.length - 1}
                  className={`p-4 rounded-full border border-white/10 transition-all ${currentCardIndex === studyData.length - 1 ? 'opacity-10 cursor-not-allowed' : 'bg-slate-900 hover:bg-slate-800 hover:border-cyan-500/50 text-white shadow-xl active:scale-95'}`}
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                  </svg>
                </button>
              </div>

              {/* Dynamic Content */}
              {mode === GenerationMode.FLASHCARDS ? (
                <Flashcard 
                  key={studyData[currentCardIndex].id} 
                  data={studyData[currentCardIndex] as FlashcardData} 
                />
              ) : (
                <QuizCard 
                  key={studyData[currentCardIndex].id} 
                  data={studyData[currentCardIndex] as QuizData} 
                />
              )}
            </div>

            {/* Controls */}
            <div className="mt-12 flex items-center justify-center gap-6">
              <button 
                onClick={prevCard}
                disabled={currentCardIndex === 0}
                className={`lg:hidden p-4 rounded-2xl border border-white/10 transition-all ${currentCardIndex === 0 ? 'opacity-20' : 'bg-slate-900 active:scale-90'}`}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
              </button>

              <div className="flex gap-3">
                {currentCardIndex === studyData.length - 1 ? (
                  <button 
                    onClick={handleReset}
                    className="px-8 py-3 rounded-2xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold transition-all shadow-[0_0_20px_rgba(34,211,238,0.3)] hover:shadow-[0_0_25px_rgba(34,211,238,0.5)] active:scale-95"
                  >
                    Finish Session
                  </button>
                ) : (
                  <button 
                    onClick={nextCard}
                    className="px-10 py-3 rounded-2xl bg-white/10 hover:bg-white/15 border border-white/10 text-white font-semibold transition-all active:scale-95"
                  >
                    Next Question
                  </button>
                )}
              </div>

              <button 
                onClick={nextCard}
                disabled={currentCardIndex === studyData.length - 1}
                className={`lg:hidden p-4 rounded-2xl border border-white/10 transition-all ${currentCardIndex === studyData.length - 1 ? 'opacity-20' : 'bg-slate-900 active:scale-90'}`}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </div>

            <p className="text-center text-slate-500 text-xs mt-8 uppercase tracking-widest font-medium opacity-50">
              Nav: Arrow Keys • Click to Flip/Select
            </p>
          </div>
        )}

        {state === AppState.ERROR && (
          <div className="text-center max-w-md animate-in fade-in zoom-in-95">
            <div className="w-16 h-16 rounded-full bg-red-500/10 text-red-400 flex items-center justify-center mx-auto mb-6">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h2 className="text-2xl font-bold mb-3">Something went wrong</h2>
            <p className="text-slate-400 mb-8">{errorMsg}</p>
            <button 
              onClick={handleReset}
              className="w-full py-3 bg-slate-800 hover:bg-slate-700 rounded-xl font-bold transition-all active:scale-95"
            >
              Back to Start
            </button>
          </div>
        )}

      </main>

      <footer className="p-8 text-center text-slate-600 text-xs border-t border-white/5 bg-slate-950/20">
        &copy; {new Date().getFullYear()} StudBud. High-fidelity learning powered by Gemini 3 Flash.
      </footer>
    </div>
  );
};

export default App;
